GET http://localhost:4000/ping

###
POST http://localhost:4000/auth/login

###
POST http://localhost:4000/auth/registrar
content-type: application/json

{
    "nome": "Teste",
    "email": "teste@zmail.com",
    "senha": "#Senha123",
    "telefone": "(11) 88888-9999",
    "barbeiro": false
}

###
POST http://localhost:4000/auth/login
content-type: application/json

{
    "email": "marcao@barbabrutal.app",
    "senha": "#Senha123"
}

###
POST http://localhost:4000/auth/login
content-type: application/json

{
    "email": "teste@zmail.com",
    "senha": "#Senha123"
}

###
GET http://localhost:4000/profissionais

###
GET http://localhost:4000/servicos

### 
POST http://localhost:4000/agendamentos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkMDIyNDZkLWI3ZWYtNDhlNy1iNGI0LTEyMjg2MTk2MjQyMiIsIm5vbWUiOiJUZXN0ZSIsImVtYWlsIjoidGVzdGVAem1haWwuY29tIiwidGVsZWZvbmUiOiIoMTEpIDg4ODg4LTk5OTkiLCJiYXJiZWlybyI6ZmFsc2UsInByb2Zpc3Npb25hbElkIjpudWxsLCJpYXQiOjE3NzU5NzM2NDYsImV4cCI6MTc3NzI2OTY0Nn0.k9hqY58Xqm3uWwiXgBhbBWSBtDR0po9an2zNlBOPJbk
Content-Type: application/json

{
    "data": "2026-04-13T13:00:00.000Z",
    "usuario": { "id": "4d02246d-b7ef-48e7-b4b4-122861962422" },
    "profissional": { "id": "a18ba9b7-c7ac-44d8-9f48-9c320d9963c2" },
    "servicos": [
        { "id": "08b674af-c5c2-4831-b782-fe4b819d20d4" }
    ]
}

###
GET http://localhost:4000/agendamentos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjRkMDIyNDZkLWI3ZWYtNDhlNy1iNGI0LTEyMjg2MTk2MjQyMiIsIm5vbWUiOiJUZXN0ZSIsImVtYWlsIjoidGVzdGVAem1haWwuY29tIiwidGVsZWZvbmUiOiIoMTEpIDg4ODg4LTk5OTkiLCJiYXJiZWlybyI6ZmFsc2UsInByb2Zpc3Npb25hbElkIjpudWxsLCJpYXQiOjE3NzU5NzM2NDYsImV4cCI6MTc3NzI2OTY0Nn0.k9hqY58Xqm3uWwiXgBhbBWSBtDR0po9an2zNlBOPJbk


###
GET http://localhost:4000/agendamentos/538d0f79-899d-48be-b927-a978087b036c/2026-04-13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVjZGIwYzE3LWFmM2EtNDhiMi05ZTE3LTgxNmM1Njc2YjYyZCIsIm5vbWUiOiJNYXJjw6NvIE1hY2hhZGFkYSIsImVtYWlsIjoibWFyY2FvQGJhcmJhYnJ1dGFsLmFwcCIsInRlbGVmb25lIjoiKDExKSA5OTk5OS05OTk5IiwiYmFyYmVpcm8iOnRydWUsInByb2Zpc3Npb25hbElkIjpudWxsLCJpYXQiOjE3NzU4ODY3ODksImV4cCI6MTc3NzE4Mjc4OX0.qp_qMPeO0IkbPExtPMr07CPXErNGFmp78cDTZlRPwzY

###
DELETE http://localhost:4000/agendamentos/1
Authorization: Bearer

###
GET http://localhost:4000/agendamentos/ocupacao/538d0f79-899d-48be-b927-a978087b036c/2026-04-13
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU3YjNhMzE3LWFlMmYtNDEzMy04YmI3LTI5ZTJjN2NmYzcwOCIsIm5vbWUiOiJUZXN0ZSIsImVtYWlsIjoidGVzdGVAem1haWwuY29tIiwidGVsZWZvbmUiOiIoMTEpIDg4ODg4LTk5OTkiLCJiYXJiZWlybyI6ZmFsc2UsInByb2Zpc3Npb25hbElkIjpudWxsLCJpYXQiOjE3NzU4ODYxMzYsImV4cCI6MTc3NzE4MjEzNn0.pUe-PK51XXXbzWKAP57-XQCQAVlM32Fzz7uNojjfJz0

### 
POST http://localhost:4000/profissionais
Content-Type: application/json 

{
    "nome": "Teste",
    "descricao": "Quando o assunto é barba, ninguém faz melhor que Beto Brutal! Suas lâminas afiadas são lendárias e seu estilo é inconfundível. Para um visual marcante e robusto, ele é o seu homem!",
    "email": "barbeiro@teste.com",
    "senha": "#Senha123",
    "telefone": "(11) 99999-8888",
    "imagemURL": "https://github.com/GabrielTh58/Barba-Brutal/blob/main/apps/frontend/public/profissionais/profissional-2.jpg?raw=true"
}